### ISSUE TITLE
Inference requires Cityscapes dataset

### ISSUE THREAD

**Issue by Dawars** [NVIDIA/semantic-segmentation#65]
I'm trying to run inference on my own images based on the instructions in the README:
`python -m runx.runx scripts/dump_folder.yml -i`

I'm using the docker file in the repository.

```
root@f5677617f085:/workspace/projects/semantic-segmentation# python -m runx.runx scripts/dump_folder.yml -i -n
python -m torch.distributed.launch --nproc_per_node=1 train.py --dataset cityscapes --cv 0 --syncbn --apex --fp16 --bs_val 1 --eval folder --eval_folder /workspace/datasets/budapest/moricz_incremental/images/moricz-insta --dump_assets --dump_all_images --n_scales 0.5,1.0,2.0 --snapshot /mnt/hdd/large_asset_dir/seg_weights/cityscapes_ocrnet.HRNet_Mscale_outstanding-turtle.pth --arch ocrnet.HRNet_Mscale --result_dir /workspace/datasets/budapest/moricz_incremental/masks_cityscape 
root@f5677617f085:/workspace/projects/semantic-segmentation# python -m runx.runx scripts/dump_folder.yml -i
None
Global Rank: 0 Local Rank: 0
Torch version: 1.3, 1.3.0a0+24ae9b5
**********************************************************************
ALERT: forcing cv=3 to allow all images to be evaluated
**********************************************************************
n scales [0.5, 1.0, 2.0]
dataset = cityscapes
ignore_label = 255
num_classes = 19
Traceback (most recent call last):
  File "train.py", line 601, in <module>
    main()
  File "train.py", line 340, in main
    datasets.setup_loaders(args)
  File "/workspace/projects/semantic-segmentation/datasets/__init__.py", line 157, in setup_loaders
    eval_folder=args.eval_folder)
  File "/workspace/projects/semantic-segmentation/datasets/cityscapes.py", line 125, in __init__
    self.fine_cities = cities_cv_split(self.root, mode, cfg.DATASET.CV)
  File "/workspace/projects/semantic-segmentation/datasets/cityscapes.py", line 65, in cities_cv_split
    trn_cities = ['train/' + c for c in os.listdir(trn_path)]
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/hdd/datasets/large_asset_dir/data/Cityscapes/leftImg8bit_trainvaltest/leftImg8bit/train'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train.py', '--local_rank=0', '--dataset', 'cityscapes', '--cv', '0', '--syncbn', '--apex', '--fp16', '--bs_val', '1', '--eval', 'folder', '--eval_folder', '/workspace/datasets/budapest/moricz_incremental/images/moricz-insta', '--dump_assets', '--dump_all_images', '--n_scales', '0.5,1.0,2.0', '--snapshot', '/mnt/hdd/large_asset_dir/seg_weights/cityscapes_ocrnet.HRNet_Mscale_outstanding-turtle.pth', '--arch', 'ocrnet.HRNet_Mscale', '--result_dir', '/workspace/datasets/budapest/moricz_incremental/masks_cityscape']' returned non-zero exit status 1.
```

Is there a way to do inference without downloading the dataset?

**Comment by ajtao** [comment]
Can you please try to move line https://github.com/NVIDIA/semantic-segmentation/blob/79467e4bf160606c3b545e0b77031627c400e031/datasets/cityscapes.py#L125 to just before line 134, so that the call to cities_cv_split() is not done when the mode is 'folder'. See if that works. 

We'll make a point of supporting this officially in the future.

**Comment by Dawars** [comment]
Yes it worked, thank you
