### ISSUE TITLE
train network with my own dataset

### ISSUE THREAD

**Issue by bberry25** [NVIDIA/semantic-segmentation#76]
HI, thanks for the code and I have two questions.
First, I want to train the network with my own dataset that has 4 classes and consists of 1K-2K resolution images. 
What should I do for this goal with your network? Is there any way to transfer learning with my dataset on the initial model you provided on the google drive?  

Second, I tried to do step "Train a model" with the cityscapes dataset.
But failed by torch.nn.parallel.DistributedDataParallel error. 
How can I fix this error? 
I have 4 GTX 2080 super GPUs, Cuda version is V10.1.243, and torch for 1.4.0.

**The error message is below:
Traceback (most recent call last):
  File "train.py", line 601, in <module>
    main()
  File "train.py", line 451, in main
    train(train_loader, net, optim, epoch)
  File "train.py", line 491, in train
    main_loss = net(inputs)
  File "/home/gpuc/anaconda3/envs/pt130/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuc/anaconda3/envs/pt130/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/gpuc/anaconda3/envs/pt130/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuc/mr/ss/network/ocrnet.py", line 334, in forward
    return self.two_scale_forward(inputs)
  File "/home/gpuc/mr/ss/network/ocrnet.py", line 277, in two_scale_forward
    lo_outs = self._fwd(x_lo)
  File "/home/gpuc/mr/ss/network/ocrnet.py", line 173, in _fwd
    _, _, high_level_features = self.backbone(x)
  File "/home/gpuc/anaconda3/envs/pt130/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuc/mr/ss/network/hrnetv2.py", line 401, in forward
    x = self.bn1(x)
  File "/home/gpuc/anaconda3/envs/pt130/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuc/anaconda3/envs/pt130/lib/python3.6/site-packages/apex/parallel/optimized_sync_batchnorm.py", line 85, in forward
    return SyncBatchnormFunction.apply(input, z, self.weight, self.bias, self.running_mean, self.running_var, self.eps, self.training or not self.track_running_stats, exponential_average_factor, self.process_group, self.channel_last, self.fuse_relu)
  File "/home/gpuc/anaconda3/envs/pt130/lib/python3.6/site-packages/apex/parallel/optimized_sync_batchnorm_kernel.py", line 38, in forward
    mean, var, inv_std = syncbn.welford_parallel(mean_all, var_all, count, eps)
TypeError: welford_parallel(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: float) -> List[at::Tensor]

Invoked with: tensor([[-2.0160e-02,  2.5569e-02,  0.0000e+00,  0.0000e+00, -4.7687e-01,
          4.8829e-01,  0.0000e+00,  1.1058e+00, -2.5195e-02,  5.0776e-02,
          9.8649e-01,  0.0000e+00, -4.0227e-01, -1.4714e-02,  1.1181e-02,
         -5.8420e-02,  0.0000e+00,  2.2286e-02,  0.0000e+00,  0.0000e+00,
          5.0438e-02,  6.5627e-01,  8.6666e-01,  1.1626e-02,  0.0000e+00,
          0.0000e+00,  3.4845e-01,  5.4020e-01,  3.4274e-01,  0.0000e+00,
         -6.0154e-01, -1.3539e+00,  0.0000e+00,  6.1270e-01,  1.2953e-02,
         -1.2288e-01, -1.6835e-02,  0.0000e+00,  0.0000e+00, -2.9235e-01,
         -8.3103e-01, -6.4989e-02,  8.0594e-02,  0.0000e+00, -1.9591e-02,
          0.0000e+00, -4.4098e-01, -4.1653e-01,  0.0000e+00,  7.7767e-07,
          7.0517e-01,  2.9854e-01, -2.5486e-02,  2.1535e-01,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  3.1337e-01,  2.0715e-01,  3.7242e-01,
          0.0000e+00,  4.9588e-01,  4.0755e-01, -6.0032e-01],
        [-1.3287e-02, -1.1428e-02,  0.0000e+00,  0.0000e+00, -3.4590e-01,
          3.1542e-01,  0.0000e+00,  7.2203e-01, -1.6731e-02,  3.5185e-02,
          6.4227e-01,  0.0000e+00, -4.8915e-01, -1.3063e-03,  9.8225e-03,
         -9.7063e-02,  0.0000e+00,  1.7914e-02,  0.0000e+00,  0.0000e+00,
          2.9692e-02,  4.0790e-01,  6.0704e-01,  8.8363e-03,  0.0000e+00,
          0.0000e+00,  3.7023e-01,  3.7232e-01,  2.4414e-01,  0.0000e+00,
         -3.8110e-01, -7.4766e-01,  0.0000e+00,  3.7812e-01,  7.6547e-03,
         -7.3323e-02, -1.4713e-02,  0.0000e+00,  0.0000e+00, -2.0440e-01,
         -7.1019e-01, -5.0704e-02,  6.8508e-02,  0.0000e+00, -1.9679e-02,
          0.0000e+00, -2.8076e-01, -2.9818e-01,  0.0000e+00,  5.3694e-07,
          4.0357e-01,  3.1873e-01, -1.5393e-02,  1.6285e-01,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  1.0628e-01,  2.4854e-01,  4.1865e-01,
          0.0000e+00,  2.7828e-01,  2.6778e-01, -4.5127e-01],
        [-8.3987e-03,  2.0638e-02,  0.0000e+00,  0.0000e+00, -2.5623e-01,
          2.2050e-01,  0.0000e+00,  4.8013e-01, -1.2769e-02,  2.3872e-02,
          4.0508e-01,  0.0000e+00, -4.6229e-01, -1.4760e-02,  5.6564e-03,
         -1.0322e-01,  0.0000e+00,  1.2943e-02,  0.0000e+00,  0.0000e+00,
          1.8157e-02,  2.6627e-01,  4.3186e-01, -5.3581e-04,  0.0000e+00,
          0.0000e+00,  2.9467e-01,  2.6311e-01,  1.8004e-01,  0.0000e+00,
         -2.4046e-01, -3.1798e-01,  0.0000e+00,  2.5050e-01,  4.9322e-03,
         -4.8812e-02, -8.7668e-03,  0.0000e+00,  0.0000e+00, -1.5033e-01,
         -5.5597e-01, -3.0802e-02,  4.3655e-02,  0.0000e+00, -1.2776e-02,
          0.0000e+00, -1.9529e-01, -2.1720e-01,  0.0000e+00,  3.8504e-07,
          2.5081e-01,  3.4440e-01, -1.0126e-02,  3.0559e-02,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  4.0732e-02,  2.0511e-01,  4.1797e-01,
          0.0000e+00,  1.7297e-01,  1.0639e-01, -4.3745e-01],
        [-2.1975e-02, -4.3096e-02,  0.0000e+00,  0.0000e+00, -5.1393e-01,
          4.9886e-01,  0.0000e+00,  1.1720e+00, -1.4093e-02,  4.0852e-02,
          1.0723e+00,  0.0000e+00, -5.2220e-01, -1.6062e-02,  1.6373e-02,
         -8.1796e-02,  0.0000e+00,  2.6088e-02,  0.0000e+00,  0.0000e+00,
          4.5129e-02,  6.7860e-01,  9.3069e-01,  1.3363e-02,  0.0000e+00,
          0.0000e+00,  4.7867e-01,  5.7650e-01,  3.6603e-01,  0.0000e+00,
         -6.3852e-01, -1.5054e+00,  0.0000e+00,  6.2479e-01,  1.3062e-02,
         -1.2200e-01, -2.3248e-02,  0.0000e+00,  0.0000e+00, -3.0834e-01,
         -9.7524e-01, -6.3470e-02,  1.0795e-01,  0.0000e+00, -1.7814e-02,
          0.0000e+00, -4.4605e-01, -4.4776e-01,  0.0000e+00,  8.3986e-07,
          7.0284e-01,  2.9554e-01, -1.8121e-02,  3.5510e-01,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  2.5356e-01,  3.0437e-01,  4.2695e-01,
          0.0000e+00,  4.8697e-01,  5.2689e-01, -5.3160e-01]], device='cuda:2'), tensor([[7.0611e-03, 3.6971e-03, 0.0000e+00, 0.0000e+00, 4.7695e-02, 7.6253e-02,
         0.0000e+00, 3.6807e-01, 4.4959e-02, 7.0671e-02, 2.9322e-01, 0.0000e+00,
         7.6705e-03, 8.2486e-01, 3.7232e-04, 2.0001e-03, 0.0000e+00, 1.7299e-03,
         0.0000e+00, 0.0000e+00, 4.7658e-02, 1.5084e-01, 1.8160e-01, 3.0682e-01,
         0.0000e+00, 0.0000e+00, 4.5425e-03, 7.3610e-02, 2.6099e-02, 0.0000e+00,
         1.1978e-01, 7.7131e-01, 0.0000e+00, 1.2486e-01, 6.0442e-05, 5.4550e-03,
         3.7419e-02, 0.0000e+00, 0.0000e+00, 2.0158e-02, 7.3825e-02, 3.9248e-01,
         9.8697e-04, 0.0000e+00, 4.3888e-01, 0.0000e+00, 6.6904e-02, 4.4410e-02,
         0.0000e+00, 1.8811e-13, 1.9579e-01, 5.9496e-03, 5.2674e-02, 1.4783e-02,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 7.7564e-02, 2.2178e-03, 5.3360e-03,
         0.0000e+00, 1.0255e-01, 5.1021e-02, 7.5157e-02],
        [9.5601e-03, 2.1591e-02, 0.0000e+00, 0.0000e+00, 8.9552e-02, 1.5103e-01,
         0.0000e+00, 6.9444e-01, 7.0298e-02, 9.7594e-02, 5.3153e-01, 0.0000e+00,
         2.9826e-02, 1.4058e+00, 5.7719e-04, 4.5479e-03, 0.0000e+00, 5.1275e-03,
         0.0000e+00, 0.0000e+00, 4.9973e-02, 2.9525e-01, 3.3713e-01, 3.9538e-01,
         0.0000e+00, 0.0000e+00, 2.0711e-02, 1.3912e-01, 4.9986e-02, 0.0000e+00,
         2.2125e-01, 1.3367e+00, 0.0000e+00, 2.5061e-01, 1.2315e-04, 1.1404e-02,
         7.2876e-02, 0.0000e+00, 0.0000e+00, 3.9440e-02, 1.2044e-01, 6.2641e-01,
         1.6006e-03, 0.0000e+00, 5.6131e-01, 0.0000e+00, 1.3496e-01, 8.0798e-02,
         0.0000e+00, 3.1782e-13, 4.0281e-01, 2.0243e-02, 5.4077e-02, 4.1210e-02,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 1.8775e-01, 1.5995e-02, 1.3982e-02,
         0.0000e+00, 2.1503e-01, 7.9489e-02, 2.2773e-01],
        [1.8453e-03, 3.6976e-03, 0.0000e+00, 0.0000e+00, 1.8262e-02, 2.8889e-02,
         0.0000e+00, 1.3585e-01, 1.4654e-02, 2.5381e-02, 1.0685e-01, 0.0000e+00,
         1.1811e-02, 3.4456e-01, 1.4230e-04, 1.0837e-03, 0.0000e+00, 3.1594e-03,
         0.0000e+00, 0.0000e+00, 8.3797e-03, 5.5142e-02, 6.8384e-02, 1.1568e-01,
         0.0000e+00, 0.0000e+00, 9.0958e-03, 2.7532e-02, 9.8368e-03, 0.0000e+00,
         4.4198e-02, 2.6968e-01, 0.0000e+00, 4.6359e-02, 2.2060e-05, 2.0487e-03,
         1.4395e-02, 0.0000e+00, 0.0000e+00, 7.6016e-03, 3.6409e-02, 1.6440e-01,
         5.5455e-04, 0.0000e+00, 1.6256e-01, 0.0000e+00, 2.5494e-02, 1.6913e-02,
         0.0000e+00, 6.7707e-14, 7.2421e-02, 4.2251e-03, 8.9992e-03, 1.1562e-02,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 3.1587e-02, 5.2741e-03, 5.6565e-03,
         0.0000e+00, 3.8412e-02, 2.0728e-02, 3.6548e-02],
        [3.0998e-03, 1.3795e-02, 0.0000e+00, 0.0000e+00, 1.8798e-02, 4.3462e-02,
         0.0000e+00, 1.7083e-01, 3.8899e-02, 7.0108e-02, 1.1556e-01, 0.0000e+00,
         2.8282e-02, 5.3916e-01, 1.9914e-04, 2.9292e-03, 0.0000e+00, 1.4743e-03,
         0.0000e+00, 0.0000e+00, 2.2752e-02, 7.9386e-02, 7.4971e-02, 1.4768e-01,
         0.0000e+00, 0.0000e+00, 1.7829e-02, 3.2091e-02, 1.1125e-02, 0.0000e+00,
         5.6042e-02, 2.7657e-01, 0.0000e+00, 7.1122e-02, 3.6140e-05, 3.5307e-03,
         1.6062e-02, 0.0000e+00, 0.0000e+00, 9.4198e-03, 1.2069e-02, 2.7675e-01,
         4.7274e-04, 0.0000e+00, 2.2111e-01, 0.0000e+00, 4.0463e-02, 1.8812e-02,
         0.0000e+00, 8.7543e-14, 1.2312e-01, 4.8573e-03, 2.5565e-02, 1.3638e-02,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 7.9322e-02, 1.5316e-02, 6.7312e-03,
         0.0000e+00, 6.9101e-02, 6.3986e-03, 8.8944e-02]], device='cuda:2'), 131072, 1e-05

**Comment by ajtao** [comment]
Could you please share the command you used? In the canonical `train_cityscapes.yml` recipe, we hardcode the # of GPUs to 8 with `--nproc_per_node=8`. You'll have to change that to 4, to start with.

**Comment by ajtao** [comment]
Also, can i ask if you were using our Dockerfile to create your docker image? I'm wondering if apex is up to date?

**Comment by bberry25** [comment]
I didn't use the Dockerfile and changed GPUs to 4 with --nproc_per_node=4.
Apex was up to date but there was an issue, too.
Anyway, I'm trying all the process again within the new environment.
Which version of PyTorch, touch vision, and Cuda is stable for this code in Ubuntu 18.04.

**Comment by ajtao** [comment]
pytorch 1.3, 1.4 should work fine with this code.

**Comment by bberry25** [comment]
Hi, I have a question about the value of --nproc_per_node. The memory of RTX 2080 super is 8G. 
I have 4 GPUs and the sum of memory will be about 32G.
But in the train_cityscapes.yml file, it said "Requires 32GB for GPU" does it mean that 32GB for 1 GPU?  
Is that possible to train the cityscapes with 4 RTX 2080 super? 

I didn't use the docker and rebuilt successfully the environment for the code. 
When I use python -m runx.runx scripts/train_cityscapes.yml -i, the log stopped and show any changes in the terminal. Is this a normal training process...? 
The last messages are below:

gpu-c@gpuc:~/mr/ss$ python -m runx.runx scripts/train_cityscapes.yml -i
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
None
Global Rank: 1 Local Rank: 1
None
Global Rank: 2 Local Rank: 2
None
Global Rank: 0 Local Rank: 0
None
Global Rank: 3 Local Rank: 3
Torch version: 1.3, 1.3.1
n scales [0.5, 1.0, 2.0]
dataset = cityscapes
ignore_label = 255
num_classes = 19
cv split val 0 ['val/lindau', 'val/frankfurt', 'val/munster']
mode val found 500 images
cn num_classes 19
cv split train 0 ['train/aachen', 'train/bochum', 'train/bremen', 'train/cologne', 'train/darmstadt', 'train/dusseldorf', 'train/erfurt', 'train/hamburg', 'train/hanover', 'train/jena', 'train/krefeld', 'train/monchengladbach', 'train/strasbourg', 'train/stuttgart', 'train/tubingen', 'train/ulm', 'train/weimar', 'train/zurich']
mode train found 2975 images
cn num_classes 19
Loading centroid file /home/gpu-c/ssdata/assets/uniform_centroids/cityscapes_cv0_tile1024.json
Found 19 centroids
Class Uniform Percentage: 0.5
Class Uniform items per Epoch: 2975
cls 0 len 5866
cls 1 len 5184
cls 2 len 5678
cls 3 len 1312
cls 4 len 1723
cls 5 len 5656
cls 6 len 2769
cls 7 len 4860
cls 8 len 5388
cls 9 len 2440
cls 10 len 4722
cls 11 len 3719
cls 12 len 1239
cls 13 len 5075
cls 14 len 444
cls 15 len 348
cls 16 len 188
cls 17 len 575
cls 18 len 2238
Using Cross Entropy Loss
Loading weights from: checkpoint=/home/gpu-c/ssdata/assets/seg_weights/ocrnet.HRNet_industrious-chicken.pth
=> init weights from normal distribution
=> loading pretrained model /home/gpu-c/ssdata/assets/seg_weights/hrnetv2_w48_imagenet_pretrained.pth
Trunk: hrnetv2
Model params = 72.1M
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Skipped loading parameter module.ocr.cls_head.weight
Skipped loading parameter module.ocr.cls_head.bias
Skipped loading parameter module.ocr.aux_head.2.weight
Skipped loading parameter module.ocr.aux_head.2.bias
Skipped loading parameter module.scale_attn.conv0.weight
Skipped loading parameter module.scale_attn.bn0.weight
Skipped loading parameter module.scale_attn.bn0.bias
Skipped loading parameter module.scale_attn.bn0.running_mean
Skipped loading parameter module.scale_attn.bn0.running_var
Skipped loading parameter module.scale_attn.bn0.num_batches_tracked
Skipped loading parameter module.scale_attn.conv1.weight
Skipped loading parameter module.scale_attn.bn1.weight
Skipped loading parameter module.scale_attn.bn1.bias
Skipped loading parameter module.scale_attn.bn1.running_mean
Skipped loading parameter module.scale_attn.bn1.running_var
Skipped loading parameter module.scale_attn.bn1.num_batches_tracked
Skipped loading parameter module.scale_attn.conv2.weight
Class Uniform Percentage: 0.5
Class Uniform items per Epoch: 2975
cls 0 len 5866
cls 1 len 5184
cls 2 len 5678
cls 3 len 1312
cls 4 len 1723
cls 5 len 5656
cls 6 len 2769
cls 7 len 4860
cls 8 len 5388
cls 9 len 2440
cls 10 len 4722
cls 11 len 3719
cls 12 len 1239
cls 13 len 5075
cls 14 len 444
cls 15 len 348
cls 16 len 188
cls 17 len 575
cls 18 len 2238

**Comment by AmazingC** [comment]
@bberry25 I have the same problem. When I run the code with train_cityscapes.yml or train_cityscapes_sota.yml, one subprocess exited without any error log and blocked the training process.
Did you have solved this problem?
