### ISSUE TITLE
Getting a `non-zero exit status 1` when running inference on cityscapes.

### ISSUE THREAD

**Issue by bohare** [NVIDIA/semantic-segmentation#93]
Hi, thanks for sharing the work. 

I am trying to run the inference on Cityscapes dataset using `python -m runx.runx scripts/eval_cityscapes.yml -i` . But I am getting the error as describe din the title. The entire trace-back is:

```
Copying codebase to logs/eval_cityscapes/cordial-goat_2020.11.11_08.30 ...
Running job eval_cityscapes_cordial-goat_2020.11.11_08.30
cd logs/eval_cityscapes/cordial-goat_2020.11.11_08.30/code; PYTHONPATH=logs/eval_cityscapes/cordial-goat_2020.11.11_08.30/code exec python -m torch.distributed.launch --nproc_per_node=1 ~/semantic-segmentation/train.py --dataset cityscapes --cv 0 --syncbn --apex --fp16 --bs_val 1 --eval val --n_scales 0.5,1.0,2.0 --snapshot /home/rbohare/assets_for_nvidiasemseg/seg_weights/cityscapes_ocrnet.HRNet_Mscale_outstanding-turtle.pth --arch ocrnet.HRNet_Mscale --result_dir logs/eval_cityscapes/cordial-goat_2020.11.11_08.30 
None
Global Rank: 0 Local Rank: 0
Torch version: 1.6, 1.6.0
n scales [0.5, 1.0, 2.0]
dataset = cityscapes
ignore_label = 255
num_classes = 19
/bin/sh: 1: cd: can't cd to logs/eval_cityscapes/cordial-goat_2020.11.11_08.30/code
Traceback (most recent call last):
  File "/home/rbohare/semantic-segmentation/train.py", line 601, in <module>
    main()
  File "/home/rbohare/semantic-segmentation/train.py", line 340, in main
    datasets.setup_loaders(args)
  File "/home/rbohare/semantic-segmentation/datasets/__init__.py", line 157, in setup_loaders
    eval_folder=args.eval_folder)
  File "/home/rbohare/semantic-segmentation/datasets/cityscapes.py", line 133, in __init__
    self.fine_cities = cities_cv_split(self.root, mode, cfg.DATASET.CV)
  File "/home/rbohare/semantic-segmentation/datasets/cityscapes.py", line 65, in cities_cv_split
    trn_cities = ['train/' + c for c in os.listdir(trn_path)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/rbohare/assets_for_nvidiasemseg/data/Cityscapes/leftImg8bit_trainvaltest/leftImg8bit/train'
Traceback (most recent call last):
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/rbohare/anaconda3/envs/nvidia-sdc/bin/python', '-u', '/home/rbohare/semantic-segmentation/train.py', '--local_rank=0', '--dataset', 'cityscapes', '--cv', '0', '--syncbn', '--apex', '--fp16', '--bs_val', '1', '--eval', 'val', '--n_scales', '0.5,1.0,2.0', '--snapshot', '/home/rbohare/assets_for_nvidiasemseg/seg_weights/cityscapes_ocrnet.HRNet_Mscale_outstanding-turtle.pth', '--arch', 'ocrnet.HRNet_Mscale', '--result_dir', 'logs/eval_cityscapes/cordial-goat_2020.11.11_08.30']' returned non-zero exit status 1.

```

I have changed `--nproc_per_node=8` to `--nproc_per_node=1` since I only have one GPU with 6G memory. Other parameters are the same. Any ideas how to solve it?

**Comment by bohare** [comment]
Never mind, it was a problem with the path of the assets. In the `config.py` file, the path to dataset is set to `/data/Cityscapes` whereas the folder had the name `/data/cityscapes`. I fixed that but now I am getting a CUDA OOM error:

```
Copying codebase to logs/eval_cityscapes/brown-wren_2020.11.11_08.46 ...
Running job eval_cityscapes_brown-wren_2020.11.11_08.46
cd logs/eval_cityscapes/brown-wren_2020.11.11_08.46/code; PYTHONPATH=logs/eval_cityscapes/brown-wren_2020.11.11_08.46/code exec python -m torch.distributed.launch --nproc_per_node=1 ~/semantic-segmentation/train.py --dataset cityscapes --cv 0 --syncbn --apex --fp16 --bs_val 1 --eval val --n_scales 0.5,1.0,2.0 --snapshot /home/rbohare/assets_for_nvidiasemseg/seg_weights/cityscapes_ocrnet.HRNet_Mscale_outstanding-turtle.pth --arch ocrnet.HRNet_Mscale --result_dir logs/eval_cityscapes/brown-wren_2020.11.11_08.46 
None
Global Rank: 0 Local Rank: 0
Torch version: 1.6, 1.6.0
n scales [0.5, 1.0, 2.0]
dataset = cityscapes
ignore_label = 255
num_classes = 19
cv split val 0 ['val/munster', 'val/lindau', 'val/frankfurt']
mode val found 500 images
cn num_classes 19
Using Cross Entropy Loss
Using Cross Entropy Loss
Loading weights from: checkpoint=/home/rbohare/assets_for_nvidiasemseg/seg_weights/cityscapes_ocrnet.HRNet_Mscale_outstanding-turtle.pth
=> init weights from normal distribution
=> loading pretrained model /home/rbohare/assets_for_nvidiasemseg/seg_weights/hrnetv2_w48_imagenet_pretrained.pth
Trunk: hrnetv2
Model params = 72.1M
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
/bin/sh: 1: cd: can't cd to logs/eval_cityscapes/brown-wren_2020.11.11_08.46/code
Traceback (most recent call last):
  File "/home/rbohare/semantic-segmentation/train.py", line 601, in <module>
    main()
  File "/home/rbohare/semantic-segmentation/train.py", line 420, in main
    calc_metrics=not args.no_metrics)
  File "/home/rbohare/semantic-segmentation/train.py", line 574, in validate
    args, val_idx)
  File "/home/rbohare/semantic-segmentation/utils/trnval_utils.py", line 141, in eval_minibatch
    output_dict = net(inputs)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rbohare/semantic-segmentation/network/ocrnet.py", line 332, in forward
    return self.nscale_forward(inputs, cfg.MODEL.N_SCALES)
  File "/home/rbohare/semantic-segmentation/network/ocrnet.py", line 224, in nscale_forward
    outs = self._fwd(x)
  File "/home/rbohare/semantic-segmentation/network/ocrnet.py", line 174, in _fwd
    cls_out, aux_out, ocr_mid_feats = self.ocr(high_level_features)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rbohare/semantic-segmentation/network/ocrnet.py", line 86, in forward
    feats = self.conv3x3_ocr(high_level_features)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 102, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/nn/functional.py", line 1119, in relu
    result = torch.relu(input)
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 5.80 GiB total capacity; 2.95 GiB already allocated; 5.12 MiB free; 4.52 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/rbohare/anaconda3/envs/nvidia-sdc/bin/python', '-u', '/home/rbohare/semantic-segmentation/train.py', '--local_rank=0', '--dataset', 'cityscapes', '--cv', '0', '--syncbn', '--apex', '--fp16', '--bs_val', '1', '--eval', 'val', '--n_scales', '0.5,1.0,2.0', '--snapshot', '/home/rbohare/assets_for_nvidiasemseg/seg_weights/cityscapes_ocrnet.HRNet_Mscale_outstanding-turtle.pth', '--arch', 'ocrnet.HRNet_Mscale', '--result_dir', 'logs/eval_cityscapes/brown-wren_2020.11.11_08.46']' returned non-zero exit status 1.

```

Is it normal to get this error while only running inference? 

I am unable to understand why 6G is not enough for running inference or a demo on one image.

**Comment by bohare** [comment]
Running the evaluation with `n_scales` parameter disabled makes it execute normally, with an IOU of ~86.56 . Might be that because of inferring on multiple scales of the image simultaneously makes the GPU run out of memory.

**Comment by ajtao** [comment]
Yes exactly

**Comment by bohare** [comment]
Thanks for confirming it. I will close the issue for now.
