### ISSUE TITLE
How to prepare the A2D2 dataset for training?

### ISSUE THREAD

**Issue by bohare** [NVIDIA/semantic-segmentation#95]
[A2D2](https://www.a2d2.audi/a2d2/en.html) is an autonomous driving dataset recently provided by Audi. It is in a slightly different format from Cityscapes in the sense that there are no explicit `train`, `val`, and `test` splits within the dataset. It is rather present in a format of multiple timestamped folders with various images and their corresponding masks. 

Is there a way to prepare the dataset so that the network can be trained on it using the `train.py` script? Since this question is more about the dataset than about the code (the code also needs to be modified though), any pointers as to how to prepare it, or how can I modify the scripts, etc. are much appreciated. Thanks!

**Comment by ajtao** [comment]
Something like what was done in cityscapes, here https://github.com/NVIDIA/semantic-segmentation/blob/main/datasets/cityscapes.py#L133-L135, would have to be done. I would suggest to split the train/val with certain cities going to either train or val but not both, which is what is done for Cityscapes.

**Comment by bohare** [comment]
Thanks for the tip. I structured the A2D2 dataset in Cityscapes format and modified the relevant methods as suggested. Upon testing the Loader class for A2D2, I got the error `ValueError: too many values to unpack (expected 2)` from [this](https://github.com/NVIDIA/semantic-segmentation/blob/9cd5bac2a4de70d5469226985d32637a0d9f7e41/datasets/uniform.py#L74) statement. 

Upon debugging, I found out that the reason is because the masks used for Cityscapes are [grayscale](https://github.com/NVIDIA/semantic-segmentation/blob/9cd5bac2a4de70d5469226985d32637a0d9f7e41/datasets/cityscapes.py#L210) whereas the only masks available for A2D2 are RGB images, therefore the reason for the error since there are 3 dimensions in A2D2 masks. 

My question is, is there a reason to use the `labelIds`-masks and not the `color` (RGB) ones, as they are also available for Cityscapes. And if you can kindly point me in a direction to proceed with the RGB masks. How can I use the RGB masks  for the training procedure? Thanks!

**Comment by bohare** [comment]
I wrote a small script to convert the RGB masks to their grayscale versions successfully. I will continue with the rest of the pipeline and update this issue as I proceed.

**Comment by bohare** [comment]
@ajtao After converting all the masks into grayscale, I successfully managed to build the centroid file for the dataset but right after it, I got the error: 

```
Traceback (most recent call last):
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rbohare/semantic-segmentation/datasets/a2d2.py", line 213, in <module>
    a2d2 = Loader(mode = "train")
  File "/home/rbohare/semantic-segmentation/datasets/a2d2.py", line 105, in __init__
    self.build_epoch()
  File "/home/rbohare/semantic-segmentation/datasets/base_loader.py", line 71, in build_epoch
    self.train)
  File "/home/rbohare/semantic-segmentation/datasets/uniform.py", line 315, in build_epoch
    msg = "cls {} len {}".format(class_id, len(centroids[class_id]))
KeyError: 19
```
It makes sense since A2D2 has 50 classes whereas for Cityscapes, the code is using 19. Any ideas how/where to modify the code to get it working?

**Comment by ajtao** [comment]
The number of classes needs to be specified in dataset_class.num_classes, such as: https://github.com/NVIDIA/semantic-segmentation/blob/main/datasets/cityscapes.py#L106, and that value is then passed into the uniform() routine: https://github.com/NVIDIA/semantic-segmentation/blob/main/datasets/cityscapes.py#L138-L142

**Comment by bohare** [comment]
Thanks for the response. I specified the `num_classes` variable to be 50. The strange thing is that the first time centroid file is built, it runs normally but every time after that, it throws the same error: `KeyError: 19`. So every time I want to make a small change in the configuration file, I have to rebuild the centroid file from scratch. Any ideas why it might be so?

**Comment by ajtao** [comment]
If you've set num_classes by defining it within the class file (like https://github.com/NVIDIA/semantic-segmentation/blob/main/datasets/cityscapes.py#L106) then you should be fine.
If you've set num_classes dynamically by overriding it after instantiating the object, then that's wrong because we capture the num_classes value very early here: https://github.com/NVIDIA/semantic-segmentation/blob/main/datasets/__init__.py#L60-L61.

**Comment by bohare** [comment]
Thanks for the comment. :) 
I did set `num_classes` to be 50 within the A2D2 class file, and nowhere else. However, I still get the same `KeyError: 19` upon starting the training after the centroid file is loaded:

```
Copying codebase to logs/train_a2d2/ocrnet.HRNet_Mscale_futuristic-otter_2020.11.27_14.02 ...
Running job train_a2d2_ocrnet.HRNet_Mscale_futuristic-otter_2020.11.27_14.02
cd logs/train_a2d2/ocrnet.HRNet_Mscale_futuristic-otter_2020.11.27_14.02/code; PYTHONPATH=logs/train_a2d2/ocrnet.HRNet_Mscale_futuristic-otter_2020.11.27_14.02/code exec python -m torch.distributed.launch --nproc_per_node=1 ~/semantic-segmentation/train.py --dataset a2d2 --cv 0 --syncbn --apex --fp16 --crop_size 1208,1920 --bs_trn 1 --poly_exp 2 --lr 5e-3 --max_epoch 175 --supervised_mscale_loss_wt 0.05 --snapshot ASSETS_PATH/seg_weights/ocrnet.HRNet_industrious-chicken.pth --arch ocrnet.HRNet_Mscale --result_dir logs/train_a2d2/ocrnet.HRNet_Mscale_futuristic-otter_2020.11.27_14.02 
None
Global Rank: 0 Local Rank: 0
Torch version: 1.6, 1.6.0
dataset = a2d2
ignore_label = 255
num_classes = 50
cv split val 0 ['val/20181108_084007', 'val/20181108_103155', 'val/20181108_091945']
mode val found 6503 images
cn num_classes 50
cv split train 0 ['train/20180807_145028', 'train/20180810_142822', 'train/20180925_101535', 'train/20180925_112730', 'train/20180925_124435', 'train/20180925_135056', 'train/20181008_095521', 'train/20181016_082154', 'train/20181016_095036', 'train/20181016_125231', 'train/20181107_132300', 'train/20181107_132730', 'train/20181107_133258', 'train/20181107_133445']
mode train found 24710 images
cn num_classes 50
Loading centroid file /home/rbohare/assets_for_nvidiasemseg/uniform_centroids/a2d2_cv0_tile1024.json
Found 49 centroids
Class Uniform Percentage: 0.5
Class Uniform items per Epoch: 24710
cls 0 len 21492
cls 1 len 17554
cls 2 len 13564
cls 3 len 299
cls 4 len 8014
cls 5 len 2247
cls 6 len 1131
cls 7 len 4
cls 8 len 10537
cls 9 len 2980
cls 10 len 767
cls 11 len 11688
cls 12 len 1974
cls 13 len 257
cls 14 len 2384
cls 15 len 350
cls 16 len 192
cls 17 len 8760
cls 18 len 11
/bin/sh: 1: cd: can't cd to logs/train_a2d2/ocrnet.HRNet_Mscale_futuristic-otter_2020.11.27_14.02/code
Traceback (most recent call last):
  File "/home/rbohare/semantic-segmentation/train.py", line 601, in <module>
    main()
  File "/home/rbohare/semantic-segmentation/train.py", line 340, in main
    datasets.setup_loaders(args)
  File "/home/rbohare/semantic-segmentation/datasets/__init__.py", line 182, in setup_loaders
    label_transform=target_train_transform)
  File "/home/rbohare/semantic-segmentation/datasets/a2d2.py", line 105, in __init__
    self.build_epoch()
  File "/home/rbohare/semantic-segmentation/datasets/base_loader.py", line 71, in build_epoch
    self.train)
  File "/home/rbohare/semantic-segmentation/datasets/uniform.py", line 317, in build_epoch
    msg = "cls {} len {}".format(class_id, len(centroids[class_id]))
KeyError: 19
Traceback (most recent call last):
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/rbohare/anaconda3/envs/nvidia-sdc/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/rbohare/anaconda3/envs/nvidia-sdc/bin/python', '-u', '/home/rbohare/semantic-segmentation/train.py', '--local_rank=0', '--dataset', 'a2d2', '--cv', '0', '--syncbn', '--apex', '--fp16', '--crop_size', '1208,1920', '--bs_trn', '1', '--poly_exp', '2', '--lr', '5e-3', '--max_epoch', '175', '--supervised_mscale_loss_wt', '0.05', '--snapshot', 'ASSETS_PATH/seg_weights/ocrnet.HRNet_industrious-chicken.pth', '--arch', 'ocrnet.HRNet_Mscale', '--result_dir', 'logs/train_a2d2/ocrnet.HRNet_Mscale_futuristic-otter_2020.11.27_14.02']' returned non-zero exit status 1.
```

But there is no such error when I delete the existing centroid file and run the training again. Then the file is created anew and the code stops at a CUDA error (but that's due to insufficient memory on my computer). I am wondering why the code stops reading the file at class 19.

**Comment by ajtao** [comment]
I'm out of ideas. I suggest running a debugger to figure this out.

**Comment by bohare** [comment]
Thanks for the suggestion. Yes, I'll try it out. :)

**Comment by nikhilbyte** [comment]
Any updates ?

**Comment by bohare** [comment]
@nikhilbyte Not regarding the centroid file but I wrote the data loader for A2D2 and waiting for the server to try out the training.

**Comment by SupriyaB1** [comment]
Hi @bohare , can you please let me know how did you convert RGB masks to gray scale masks. 
Thank you.

**Comment by medmonds91** [comment]
`KeyError:19 ` happens as the length of `cls 19` is 0, you can remove it from the dataset. This allows you to build the centroid file.

**Comment by vikasnr** [comment]
Hey @bohare did you convert from rgb to gray scale by matching the colors? or did you follow any other method to achieve this?

**Comment by bohare** [comment]
@SupriyaB1 @vikasnr I converted the RGB masks to grayscale by creating a mapping between the colors and the classes, parsing through every pixel in all images in the dataset, mapping the RGB tuple value of that pixel to a class label, and saving the new labeled images as png files to be later used in training. It does not matter what class label (ID) you assign to every class as long as it is unique. [This answer](https://stackoverflow.com/a/62179855/5847147) on SO should get you started.

**Comment by vikasnr** [comment]
Thank you @bohare 

Finding materials on a2d2 has been a bit challenging. Cityscapes and BDD have github repos that are useful. Fair amount of benchmarking have been done on these. For instance I didn't find classes labels anywhere for a2d2 but only buried inside ~160GB archive.

**Comment by vikasnr** [comment]
@bohare 
I seem to have hit roadblock, I downloaded "Dataset - Semantic Segmentation". There is a "class_list.json" file which has hex to class mapping like so
```
{
    "#ff0000": "Car 1",
    "#c80000": "Car 2",
    "#960000": "Car 3",
    "#800000": "Car 4",
     ...
```
I converted them to rgb 

```
{
    (255, 0, 0): 'Car 1', 
    (200, 0, 0): 'Car 2', 
    (150, 0, 0): 'Car 3',
    (128, 0, 0): 'Car 
    ...
```

However there seems to be inconsistency in the labels.

Consider this 
![Dashed line_20180925101535_camera_frontcenter_000028630](https://user-images.githubusercontent.com/11594098/122332782-a822fd80-cf54-11eb-8ab1-8326c8ae7b82.png)

![Dashed line_label20180925101535_camera_frontcenter_000028630](https://user-images.githubusercontent.com/11594098/122332796-b113cf00-cf54-11eb-835e-ebbbb865ea59.png)

Printing unique pixels with their corresponding labels.
```
original_rgb_class = {
    (255, 0, 0): 'Car 1', 
    (200, 0, 0): 'Car 2', 
    (150, 0, 0): 'Car 3',
    (128, 0, 0): 'Car 
    ...
}
find_labels(image)

(255, 0, 255)		 RD normal street
(200, 150, 180)		 None
(0, 0, 150)		 None
(37, 193, 255)		 None
(194, 253, 147)		 None
(0, 128, 255)		 Traffic signal 1
(0, 0, 255)		 None
(128, 0, 255)		 Dashed line
(255, 206, 135)		 None
(255, 153, 204)		 None
(108, 99, 139)		 None
(177, 44, 33)		 None
(0, 0, 200)		 None
(64, 0, 64)		 Irrelevant signs
(0, 128, 128)		 None
(150, 0, 150)		 RD restricted area
(143, 246, 255)		 None
(255, 255, 0)		 Utility vehicle 1
(210, 125, 200)		 None
(180, 50, 180)		 Drivable cobblestone
(255, 128, 0)		 Truck 1
(255, 0, 128)		 Obstacles / trash
(255, 230, 241)		 None

```

The pixels in the label image does seem to match with the classes provided.

Am I looking at a different class label list? Do let me know if you find where I'm going wrong.

[Dataset I downloaded](https://aev-autonomous-driving-dataset.s3.eu-central-1.amazonaws.com/camera_lidar_semantic.tar)
[class_list.txt](https://github.com/NVIDIA/semantic-segmentation/files/6667439/class_list.txt)

**Comment by vikasnr** [comment]
It was silly of me, cv2 reads in BGR but class mapping is in RGB. Apologies for spamming the thread.

**Comment by omar-hamim** [comment]
> I wrote a small script to convert the RGB masks to their grayscale versions successfully. I will continue with the rest of the pipeline and update this issue as I proceed.

Hi Bohare,
I have been stuck at this point while applying segmentation on my custom images. I tried to use grayscale converter of opencv but it is giving error while updating the validation loss. Can you please share your code on how to convert our RGB images to grayscale images keeping in line with the Cityscapes classes?

Thanking you,
Omar
