### ISSUE TITLE
training error OCR with ResNet-34 trunk (mutiscale mode)

### ISSUE THREAD

**Issue by adeshkin** [NVIDIA/semantic-segmentation#96]
Traceback (most recent call last):
  File "train.py", line 601, in <module>
    main()
  File "train.py", line 451, in main
    train(train_loader, net, optim, epoch)
  File "train.py", line 491, in train
    main_loss = net(inputs)
  File "/home/adeshkin/.conda/envs/hier_seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/adeshkin/.conda/envs/hier_seg/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/adeshkin/.conda/envs/hier_seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/adeshkin/projects/sem_seg/hier/semantic-segmentation/network/ocrnet.py", line 334, in forward
    return self.two_scale_forward(inputs)
  File "/home/adeshkin/projects/sem_seg/hier/semantic-segmentation/network/ocrnet.py", line 277, in two_scale_forward
    lo_outs = self._fwd(x_lo)
  File "/home/adeshkin/projects/sem_seg/hier/semantic-segmentation/network/ocrnet.py", line 173, in _fwd
    _, _, high_level_features = self.backbone(x)
  File "/home/adeshkin/.conda/envs/hier_seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/adeshkin/projects/sem_seg/hier/semantic-segmentation/network/utils.py", line 110, in forward
    **x = self.layer3(x)**
  File "/home/adeshkin/.conda/envs/hier_seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/adeshkin/.conda/envs/hier_seg/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/adeshkin/.conda/envs/hier_seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/adeshkin/projects/sem_seg/hier/semantic-segmentation/network/Resnet.py", line 91, in forward
    **out += residual**
  File "/home/adeshkin/.conda/envs/hier_seg/lib/python3.6/site-packages/apex/amp/wrap.py", line 53, in wrapper
    return orig_fn(*args, **kwargs)
**RuntimeError: The size of tensor a (32) must match the size of tensor b (64) at non-singleton dimension 3**

**Comment by adeshkin** [comment]
just change **conv2 to conv1** on https://github.com/NVIDIA/semantic-segmentation/blob/9cd5bac2a4de70d5469226985d32637a0d9f7e41/network/utils.py#L73 and https://github.com/NVIDIA/semantic-segmentation/blob/9cd5bac2a4de70d5469226985d32637a0d9f7e41/network/utils.py#L78
